### ISSUE TITLE
Issue with react useCallback and other functions which are typed to return the function given.

### ISSUE THREAD

**Issue by UncleClapton** [imliam/vscode-inline-parameters#19]
Hey there! It seems like this plugin is getting confused by react's `useCallback` function, and other memoization funcs.

if the function you're passing accepts no arguments, the name displayed appears like this:

![](https://clapton.dev/u/2006/0008a51a.png)

When the function accepts an argument, the name takes on whatever name that argument is.

![](https://clapton.dev/u/2006/4be213a6.png)

In both of these cases, the name given to this parameter should be `callback`

**Comment by yume-chan** [comment]
Duplicate of #10

**Comment by UncleClapton** [comment]
Ah totally missed that one. I'll close this one then.
