### ISSUE TITLE
Allow for customizable background

### ISSUE THREAD

**Issue by williamleiby** [imliam/vscode-inline-parameters#27]
The extension is great as it takes inspiration from the great inlay hints IntelliJ and other JetBrains products offer, but it would be great to see a setting that would look like this:

`"inline-parameters.backgroundColor": "#123456",`

You could pass hex code values or rgb/rgba values along with `false` if you wanted a transparent background as well!

This would alter the background color behind the text of the inlay hints. I'm currently using a One Dark Pro theme and this is what the hinting looks like:

![Axios Inline Parameter](https://user-images.githubusercontent.com/31943923/91580648-0540ba80-e913-11ea-81e7-52f3e6d5ea21.png)

The idea would be to alter the coloring behind `url: `

**Comment by imliam** [comment]
Does the `inlineparameters.annotationBackground` theme setting not already do this as you want?

**Comment by williamleiby** [comment]
Here is what I am getting when I try to implement the setting as you described:
![new-screenshot 2020-08-28 at 10 27 54 AM](https://user-images.githubusercontent.com/31943923/91585186-55228000-e919-11ea-8d74-9fdf98de9023.png)

![new-screenshot 2020-08-28 at 10 29 36 AM](https://user-images.githubusercontent.com/31943923/91585217-6075ab80-e919-11ea-9d6b-1db50b3f4d3d.png)

The only difference between these two photos is the dash separating `inline` and `parameters` in as the JSON key as all other settings keys are typed as `inline-parameters` in place of `inlineparameters `.

**Comment by imliam** [comment]
That's not what the only difference should be. As this extension's readme says, it is not a setting, it is a themeable colour customisation and needs to go within a `workbench.ColorCustomizations` object. For example:

```

  "workbench.colorCustomizations": {
    "inlineparameters.annotationBackground": "#ff0000"
  }
```

I've just tested that still works on the latest version myself and it does, so I'm going to mark this as closed. Let me know if you have any problems getting that working.
