### ISSUE TITLE
Add some more styling maybe

### ISSUE THREAD

**Issue by st-schneider** [imliam/vscode-inline-parameters#3]
it would be nice if it would look like more like the lens feature, maybe it is even doable with lens I have no idea.
Maybe give it a border or a background color to make it stand out more.
Also, if you click on it you also seem to select brackets with it.
Update: Actually it is the other way around, the bracket selection seeps in to the inline parameter. 
<img width="180" alt="image" src="https://user-images.githubusercontent.com/30625381/83980337-31046380-a915-11ea-90b5-70434a1bcc52.png">

**Comment by ryangjchandler** [comment]
@bm-stschneider You can actually change the foreground and background colour by changing the `inlineparameters.annotationForeground` and `inlineparameters.annotationBackground` values for your theme.

**Comment by st-schneider** [comment]
Well, but not in the settings.

**Comment by ryangjchandler** [comment]
> Well, but not in the settings.

I know, I was just saying that it's already possible to change the text color and background color.

**Comment by imliam** [comment]
You can actually change the colours in your settings by editing the `settings.json` file with the `workbench.colorCustomizations` key:

```json
{
  "workbench.colorCustomizations": {
    "inlineparameters.annotationForeground": "#000000",
    "inlineparameters.annotationBackground": "#ff6600",
  }
}
```

See the docs page: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by st-schneider** [comment]
Good point.

**Comment by imliam** [comment]
To cover the other point, there are now also a few additional options you can set, such as margin/padding/border.

**Comment by st-schneider** [comment]
loving it already.
![image](https://user-images.githubusercontent.com/30625381/84118292-13c5b700-aa33-11ea-9fd4-310aa90dd099.png)
