### ISSUE TITLE
font-size settings has no effect

### ISSUE THREAD

**Issue by leodr** [imliam/vscode-inline-parameters#4]
Changing the font-size in settings has no effect for me in VSCode 1.46.0-insider.

![image](https://user-images.githubusercontent.com/39763575/84002215-5c646e00-a968-11ea-94d5-a1f0d80565ed.png)

![image](https://user-images.githubusercontent.com/39763575/84002230-65553f80-a968-11ea-9c81-8ad03b73e5ad.png)

![image](https://user-images.githubusercontent.com/39763575/84002268-730ac500-a968-11ea-98ab-4e7702d80375.png)

**Comment by ryangjchandler** [comment]
Experiencing the same problem.

**Comment by iamjasinski** [comment]
Same here.

**Comment by ryangjchandler** [comment]
I've opened a PR to fix this.
