### ISSUE TITLE
VSCode's "Word Wrap: on" setting does not work correctly when this extension is enabled

### ISSUE THREAD

**Issue by luewolf** [imliam/vscode-inline-parameters#53]
`Word Wrap: on` usually disables horizontal scrolling by wrapping lines at viewport width.

With this extension enabled, the wrap is incorrectly applied (presumably because VSCode does not count the length of the inline parameters when calculating the position at which to wrap), which causes the text to exit the editor's viewport to the side for a couple of characters before it wraps, thus causing the code to be partially cut off and a horizontal scrollbar to appear.

**Comment by venus6** [comment]
I also encountered this problem. I hope the author can fix this problem.

**Comment by imliam** [comment]
Unfortunately, this seems to be something unsolvable (from any way I can figure out) issue in VSCode - there are plenty of other extensions using code lens that unfortunately suffers the same problem - some get around it by displaying the lens on a separate line entirely, but that wouldn't work for this extension.

Going to mark this as closed until there's a VSCode update that allows this to be sorted - or until VSCode's own inlay hints supports it.
